/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  KeeperRegistryInterface,
  KeeperRegistryInterfaceInterface,
} from "../KeeperRegistryInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "query",
        type: "address",
      },
    ],
    name: "getKeeperInfo",
    outputs: [
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
      {
        internalType: "uint96",
        name: "balance",
        type: "uint96",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class KeeperRegistryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): KeeperRegistryInterfaceInterface {
    return new utils.Interface(_abi) as KeeperRegistryInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KeeperRegistryInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as KeeperRegistryInterface;
  }
}
