/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GachaStateInterface extends utils.Interface {
  functions: {
    "chips(uint256)": FunctionFragment;
    "chipsCount()": FunctionFragment;
    "segments(uint256)": FunctionFragment;
    "segmentsCount()": FunctionFragment;
    "totalAmount()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "chips", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "chipsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "segments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "segmentsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAmount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "chips", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chipsCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "segments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "segmentsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface GachaState extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GachaStateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    chips(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { player: string; amount: BigNumber }>;

    chipsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    segments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    segmentsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalAmount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  chips(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { player: string; amount: BigNumber }>;

  chipsCount(overrides?: CallOverrides): Promise<BigNumber>;

  segments(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  segmentsCount(overrides?: CallOverrides): Promise<BigNumber>;

  totalAmount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    chips(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { player: string; amount: BigNumber }>;

    chipsCount(overrides?: CallOverrides): Promise<BigNumber>;

    segments(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    segmentsCount(overrides?: CallOverrides): Promise<BigNumber>;

    totalAmount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    chips(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    chipsCount(overrides?: CallOverrides): Promise<BigNumber>;

    segments(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    segmentsCount(overrides?: CallOverrides): Promise<BigNumber>;

    totalAmount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    chips(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chipsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    segments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    segmentsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
